# Generated by Django 6.0.1 on 2026-01-19 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_project_student_name_notification_project_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='المستلم'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد المراجعة'), ('accepted', 'مقبول'), ('need_work', 'بحاجة تعديل')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='report',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_reports', to=settings.AUTH_USER_MODEL, verbose_name='الطالب المرسل'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='هل قرئ؟'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(verbose_name='نص الإشعار'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.project', verbose_name='المشروع المرتبط'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(verbose_name='وصف المشروع'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('proposed', 'مقترح'), ('in_progress', 'قيد التنفيذ'), ('completed', 'منجز')], default='proposed', max_length=20, verbose_name='حالة المشروع'),
        ),
        migrations.AlterField(
            model_name='project',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='student_projects', to=settings.AUTH_USER_MODEL, verbose_name='الطلاب المشاركون'),
        ),
        migrations.AlterField(
            model_name='project',
            name='supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_projects', to=settings.AUTH_USER_MODEL, verbose_name='المشرف'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان المشروع'),
        ),
        migrations.AlterField(
            model_name='report',
            name='feedback',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات المشرف'),
        ),
        migrations.AlterField(
            model_name='report',
            name='file',
            field=models.FileField(null=True, upload_to='reports/', verbose_name='ملف التقرير'),
        ),
        migrations.AlterField(
            model_name='report',
            name='file_title',
            field=models.CharField(max_length=100, verbose_name='عنوان الملف'),
        ),
        migrations.AlterField(
            model_name='report',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='api.project', verbose_name='المشروع'),
        ),
        migrations.AlterField(
            model_name='report',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع'),
        ),
    ]
