# Generated by Django 6.0.1 on 2026-04-05 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_announcement_attendace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='Project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='api.project'),
            preserve_default=False,
        ),
    ]
