# Generated by Django 6.0.1 on 2026-04-05 18:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_announcement_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attendace',
            new_name='Attendance',
        ),
        migrations.RenameField(
            model_name='announcement',
            old_name='Project',
            new_name='project',
        ),
    ]
