# Generated by Django 6.0.1 on 2026-04-11 10:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_project_final_grade_defensecommittee_evaluation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, related_name='student_projects', to=settings.AUTH_USER_MODEL, verbose_name='الطلاب المشاركون'),
        ),
    ]
