# Generated by Django 6.0.1 on 2026-05-31 14:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_project_students'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='student_projects', to=settings.AUTH_USER_MODEL, verbose_name='الطلاب المشاركون'),
        ),
    ]
