# Generated by Django 6.0.1 on 2026-05-31 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_project_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('approved', 'مقبول'), ('rejected', 'مرفوض')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='max_students',
            field=models.PositiveBigIntegerField(default=5, verbose_name='الحد الأقصى للطلاب'),
        ),
    ]
