# Generated by Django 6.0.1 on 2026-05-31 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_project_approval_status_project_max_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_students_per_project', models.PositiveBigIntegerField(default=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='max_students',
        ),
        migrations.AddField(
            model_name='project',
            name='required_reports',
            field=models.PositiveBigIntegerField(default=8, verbose_name='عدد التقارير المطلوبة'),
        ),
    ]
