# Generated by Django 6.0.1 on 2026-06-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_department_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='رمز التحقق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('is_used', models.BooleanField(default=False, verbose_name='هل تم استخدامه؟')),
            ],
        ),
        migrations.AddField(
            model_name='announcement',
            name='title',
            field=models.CharField(default='إعلان', max_length=200, verbose_name='عنوان الإعلان'),
        ),
        migrations.AddField(
            model_name='project',
            name='deliverables',
            field=models.TextField(blank=True, verbose_name='مخرجات المشروع'),
        ),
        migrations.AddField(
            model_name='project',
            name='objectives',
            field=models.TextField(blank=True, verbose_name='أهداف المشروع'),
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.TextField(blank=True, verbose_name='التقنيات المستخدمة'),
        ),
    ]
