# Generated by Django 6.0.1 on 2026-07-01 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_setup_departments_and_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='department',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='api.department'),
        ),
        migrations.AlterField(
            model_name='project',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='api.department', verbose_name='القسم'),
        ),
    ]
