# Generated by Django 6.0.1 on 2026-07-01 14:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_systemsettings_department_alter_project_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='joinrequest',
            unique_together={('project',)},
        ),
        migrations.AddField(
            model_name='joinrequest',
            name='students',
            field=models.ManyToManyField(related_name='join_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='joinrequest',
            name='student',
        ),
    ]
